In [1]:
from scipy.stats import ks_2samp

In [7]:
import numpy as np 
d1 = np.arange(10)
d2 = np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
#to check the drift 
test= ks_2samp(d1,d2)

In [10]:
test

KstestResult(statistic=np.float64(1.0), pvalue=np.float64(5.670284308055206e-06), statistic_location=np.int64(9), statistic_sign=np.int8(1))

In [1]:
2+1

3

In [2]:
from sensor.ml.model.estimator import TargetValueMapping

In [3]:
TargetValueMapping().to_dict()

{'neg': 0, 'pos': 1}

In [4]:
TargetValueMapping().reverse_mapping()

{0: 'neg', 1: 'pos'}

In [3]:
import pandas as pd 
data = pd.read_csv(r"C:\Users\pc\Desktop\_Machine_Learning_Projects\LiveSensor\_testdata.csv")
data

,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,153204,0.0,182,NaN,0,0,0,0,0,11804,...,129862,26872,34044,22472,34362,0,0,0,0,0
1,453236,NaN,2926,NaN,0,0,0,0,222,323436,...,7908038,3026002,5025350,2025766,1160638,533834,493800,6914,0,0

In [6]:
df = pd.DataFrame(data)

In [8]:
df = df.reset_index(drop=True)
df.head()

,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,153204,0.0,182,NaN,0,0,0,0,0,11804,...,129862,26872,34044,22472,34362,0,0,0,0,0
1,453236,NaN,2926,NaN,0,0,0,0,222,323436,...,7908038,3026002,5025350,2025766,1160638,533834,493800,6914,0,0

,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,ag_004,ag_005,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,182,NaN,0,0,0,0,0,11804,684444,326536,...,129862,26872,34044,22472,34362,0,0,0,0,0
1,2926,NaN,0,0,0,0,222,323436,2999280,20657518,...,7908038,3026002,5025350,2025766,1160638,533834,493800,6914,0,0